# Generated by Django 2.1.2 on 2018-11-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='participante',
            new_name='nome',
        ),
    ]
