# Generated by Django 2.1.2 on 2018-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181107_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='area',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
